### PR TITLE
Basic controls

### LINKED ISSUE #17: [Controls] - Integrate PI(D) Controller
### Current Features

Linked to #16 

### Desired Additional Features

We need to integrate a PID controller into this pipeline. It will probably be one of the first blocks in the chain. This PID controller should be simulated in MATLAB or Python to verify that it works as intended

### Screenshots (as needed)

_No response_

### LINKED ISSUE #18: [Controls] - Integrate Park Transform into FOC
### Current Features

Linked to #16 

### Desired Additional Features

We need to integrate the Park Transform into the control pipeline. Ideally this block should be validated in Python MATLAB

### Screenshots (as needed)

_No response_

### LINKED ISSUE #19: [Controls] - Integrate Clarke Transform into FOC
### Current Features

Linked to #16 

### Desired Additional Features

We need to integrate the Clarke Transform into the control pipeline. ideally this should be tested in Python or Matlab to verify that it works

### Screenshots (as needed)

_No response_

### LINKED ISSUE #20: [Controls] - Integrate Inverse Park Transform into FOC
### Current Features

Linked to #16 and possibly #18 

### Desired Additional Features

We need to add an inverse park transform into the control pipeline for FOC. Ideally this should be validated in Matlab or Python

### Screenshots (as needed)

_No response_

### LINKED ISSUE #21: [Controls] - Integrate SVM into FOC
### Current Features

Linked to #16 

### Desired Additional Features

We need to integrate a Space Vector PWM Generator into the control pipeline. Ideally this should be validated in Python or Matlab

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by nwdepatie**
## Changes

Here is my super copy paste implementation of some basic FOC algorithms. Most of it was taken from here: https://dev.ti.com/tirex/explore/node?node=A__ALwCa95esNRP4Po9SULhNw__motor_control_c2000ware_sdk_software_package__0.jXikd__LATEST

As there is a lot of copy paste code, I've ensured that one commit is _just_ the copied files, and the other is the actual changes being made. I figured I would make one big PR for this because these are a fair amount of smaller tickets, just a LOT of code.

## Notes

For looking at what changes I made in our codebase, check `foc.c` and `foc.h`

Here is a picture of the control algorithm I am shooting for:
image

## Test Cases

- Builds for now

## To Do

_Any remaining things that need to get done_

- [ ] Future action item potentially outside of PR potentially inside of PR is to get this C code simulated in Simulink

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No merge conflicts
- [x] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #17 
Closes #18
Closes #19 
Closes #20 
Closes #21 (issue #)

### CODE REVIEW

**Comment by nwdepatie** [comment]
Note: This PR should not be automatically all squashed together to keep copying files in separate commits, it should be rebased. If anything I'll probably manually rebase and squash to consolidate commits if need be

**Comment by nwdepatie** [comment]
# BIG NOTE

I think that the setup functions are going to need to be changed in real time with measurements. Specifically the DC bus voltage and rotor position are going to need to be fed into this

**Comment by nwdepatie** [comment]
> I think that, right now, the setup functions are going to need to be changed in real time with measurements. Specifically the DC bus voltage and rotor position are going to need to be fed into this.
> 
> I think I need to rethink the how data comes in from different sources. I think I want to go with an event bus approach, where there is a message type that has an ID and the payload consists of a union of multiple different data types depending on the type of data, then feed data in with a switch to decode.

Update: Made these changes, pretty happy with how it is turning out

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
